### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by yl3362** [nicole-luisi/nicoleluisi-MADA-portfolio#3]
Good visualization! It looks like same as the original graph. I feel very lucky to view your exercise. Since the work you did is what I didn't know in my exercise. You did a good job.

Here are what you can consider:
1.you can use:
t1 <-table(starbucks$original_Store.Status, useNA = "always")
t1a <-(t1[5])
paste('Union Win ','(',t1[5],')',sep='')
above your line 60. Then you can use this method to make your label, so we won't need to change the title manually.
Just samiliar as what you did at line 67.
Good job. If there is difference, that is indiscernible to the naked eyes.

**Comment by nicole-luisi** [comment]
Thank you @yl3362! I will consider this solution with the paste option to avoid making those labels manually. This would be much better to do if the data were still being collected over time as well so that the values are always updated.
